export const CREATE_TELNUMB = 'CREATE_TELNUMB';
export const FETCH_NUMBERS = 'FETCH_NUMBERS';
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';
export const REQUEST_NUMBERS = 'REQUEST_NUMBERS';